name: carrier_info_example
description: Demonstrates how to use the carrier_info plugin.
version: 0.1.0+5

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.3.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  carrier_info:
    path: ../

  cupertino_icons: ^1.0.9
  permission_handler: ^12.0.3

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  collection: ^1.19.1
  leak_tracker: ^11.0.2
  leak_tracker_flutter_testing: ^3.0.10
  material_color_utilities: ^0.13.0
  string_scanner: ^1.4.1
  test_api: ^0.7.12

flutter:
  uses-material-design: true


