name: carrier_info
description: Carrier Info gets networkType, networkGeneration, mobileCountryCode, mobileCountryCode, e.t.c from both android and ios devices
version: 4.0.0
homepage: https://github.com/thorito/carrier_info.git

environment:
  sdk: '>=3.3.5 <4.0.0'
  flutter: '>=3.44.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  collection: ^1.19.1
  leak_tracker: ^11.0.2
  leak_tracker_flutter_testing: ^3.0.10
  lints: ^6.1.0
  material_color_utilities: ^0.13.0
  meta: ^1.18.2
  string_scanner: ^1.4.1
  test_api: ^0.7.12
  vm_service: ^15.2.0

flutter:
  plugin:
    platforms:
      android:
        package: com.chizi.carrier_info
        pluginClass: CarrierInfoPlugin
      ios:
        pluginClass: SwiftCarrierInfoPlugin
  config:
    enable-swift-package-manager: true
