name: carrier_info
description: Carrier Info gets networkType, networkGeneration, mobileCountryCode, mobileCountryCode, e.t.c from both android and ios devices
version: 3.0.5
homepage: https://github.com/thorito/carrier_info.git

environment:
  sdk: '>=3.3.5 <4.0.0'
  flutter: '>=3.24.5'

dependencies:
  flutter_lints: ^5.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  collection: ^1.19.1
  leak_tracker: ^10.0.9
  leak_tracker_flutter_testing: ^3.0.9
  lints: ^5.1.1
  material_color_utilities: ^0.12.0
  meta: ^1.16.0
  string_scanner: ^1.4.1
  test_api: ^0.7.4
  vm_service: ^15.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.chizi.carrier_info
        pluginClass: CarrierInfoPlugin
      ios:
        pluginClass: CarrierInfoPlugin